WORKING_DIR_PATH        = "/home/orin/ADB-Project/development"
MODELS_DIR_PATH         = WORKING_DIR_PATH + "/models"
DATAS_DIR_PATH          = WORKING_DIR_PATH + "/datas"

NN_MODEL_PATH           = MODELS_DIR_PATH + "/default/nn/model.pth"
NN_LABEL_ENCODER_PATH   = MODELS_DIR_PATH + "/default/nn/label_encoder.pkl"
SVM_MODEL_PATH          = MODELS_DIR_PATH + "/default/svm/model.pkl"
SVM_LABEL_ENCODER_PATH  = MODELS_DIR_PATH + "/default/svm/label_encoder.pkl"
RF_MODEL_PATH           = MODELS_DIR_PATH + "/default/rf/model.pkl"
RF_LABEL_ENCODER_PATH   = MODELS_DIR_PATH + "/default/rf/label_encoder.pkl"
